version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
       MYSQL_ROOT_PASSWORD: trawsgrifiwr
       MYSQL_DATABASE: trawsgrifiwr
       MYSQL_USER: trawsgrifiwr
       MYSQL_PASSWORD: trawsgrifiwr

  redis:
    image: redis
    restart: always
    volumes:
      - redis_data:/data

  web:
    build: "./web"
    restart: always
    entrypoint: ["supervisord","-c","service_script.conf"]
    volumes:
      - ./web/:/usr/src/app
      - ./web/data:/usr/src/app/data
    ports:
      - "6543:6543"
    depends_on:
      - db
      - redis

volumes:
  redis_data: {}
  db_data: {}
